# ============================================================
# Site Settings
# ============================================================
title:  Artificial Intelligence and Pattern Recognition
description: "Li Ping @ Hangzhou Dianzi University"

# ============================================================
# Theme
# ============================================================
remote_theme: pages-themes/cayman@v0.2.0
# theme: jekyll-theme-cayman

# ============================================================
# Social / Author Info
# ============================================================
author: Li Ping@HDU



