# ============================================================
# Site Settings
# ============================================================
title:  Artificial Intelligence and Pattern Recognition
description: "Li Ping @ Hangzhou Dianzi University"

# ============================================================
# Theme
# ============================================================
theme: jekyll-theme-cayman

# ============================================================
# Social / Author Info
# ============================================================
author: Li Ping@HDU



